### ISSUE TITLE
Module Name in .rambaspec support

### ISSUE THREAD

**Issue by MaximBazarov** [rambler-digital-solutions/Generamba#102]
Hi guys is there any chance to implement replacing `{{ module_info.name }}` with module name like it doing in liquid templates?
Example: 

```
- {name: Cell/{{ module_info.name }}TableCell.swift, path: Code/Cell/tablecell.swift.liquid}
```

Will generate: 

```
SomeModuleTableCell.swift
```

**Comment by etolstoy** [comment]
@MaksimBazarov it's already working in this way: https://github.com/rambler-ios/Generamba/wiki/Template-Structure
