### ISSUE TITLE
Author setting setup

### ISSUE THREAD

**Issue by Koshub** [rambler-digital-solutions/Generamba#107]
Is there any way to setup `author` setting for separated project?

**Comment by etolstoy** [comment]
Hi, @Koshub. No, currently it's not possible. What do you prefer:
- Setting the author name using special flag with `gen` command. e.g.: `generamba gen MyModule template --author 'Egor Tolstoy'`. If the flag is not specified, the default name is used.
- Setting the author name in the Rambafile. If the flag is not specified, the default name is used.

**Comment by Koshub** [comment]
Thanks for answer. Although both options are useful currently I would like to have setting in Rambafile. Thanks

**Comment by Koshub** [comment]
👍

**Comment by elielr01** [comment]
Just a question about this topic. Where is this "default name" stored and how can I change it.

I'm a Mac user if that helps.
