### ISSUE TITLE
Sample swift code required 

### ISSUE THREAD

**Issue by zigzagg16** [rambler-digital-solutions/Generamba#109]
Hi there !
Awesome tool, it looks like the most complete generator I've tried !
I'm quite new to VIPER, so I'd like to know if you have sample codes for VIPER Swift code ? Are we required to use a DI framework ?

Thx for helping !

**Comment by etolstoy** [comment]
Hi, @arn00s! Thanks!

You can use this [swift template](https://github.com/rambler-ios/generamba-catalog/tree/master/swifty_viper) as a starting point. 

And if you need more information on how to use VIPER, you can refer to [The Book of VIPER](https://github.com/rambler-ios/The-Book-of-VIPER). It's available only in Russian, but maybe Google.Translate can help a little.
