### ISSUE TITLE
Target membership for module sources

### ISSUE THREAD

**Issue by DevAlloy** [rambler-digital-solutions/Generamba#11]
It will be better to add module's sources to test target automatically.

**Comment by etolstoy** [comment]
That's definitely shouldn't be the default option - the source files should be included in the test target only for unit tests. Application tests (which are created by default) don't require these imports.

I think of adding another flag to `generamba gen MyModule`, something like `generamba gen MyModule --tests-include-sources`. And yes, I'm not great in inventing new namings 😁

**Comment by etolstoy** [comment]
After a short investigation I think that adding this flag is a poor design decision. A more flexible way is to use an array of project and test targets instead of the single ones. 

This issue also addresses #37.

**Comment by etolstoy** [comment]
Fixed, the new version will be released shortly, maybe even this weekend.
