### ISSUE TITLE
Project target name in module_info

### ISSUE THREAD

**Issue by Austinate** [rambler-digital-solutions/Generamba#110]
Hi! First of all — thank's for awesome project.
Recently i've faced a situation where i'd like to automatically import main module into tests via 
`@testable import MyTargetName` but, unfortunately, module_info is missing any info about app targets. 

From what i see — this will need some changes to content_generator.rb but i'm not familiar with Ruby so i'd like to get some help. 

P.S. I've managed to workaround this with `@testable import {{ module_info.project_name }}` for now but ofc that's because my Project name == my main target name.

**Comment by etolstoy** [comment]
Hi! Thanks for the feature request, we'll implement it in the next version.

**Comment by etolstoy** [comment]
In the next version you'll be able to query project and test targets in the following way:

``` liquid
{{ module_info.project_targets.first }}
{{ module_info.test_targets[2] }}
```
