### ISSUE TITLE
Gem dependency of cocoapods-core-0.39.0

### ISSUE THREAD

**Issue by Koshub** [rambler-digital-solutions/Generamba#114]
Currently available version is cocoapods-core (1.0.0). Could you change the gem dependency to cocoapods-core (1.0.0) ?

**Comment by Koshub** [comment]
Found that  `cocoapods 1.0.0` have some bugs so the issue currently is not so important

**Comment by etolstoy** [comment]
Thanks for reporting. Let's return back to this issue later, when they fix it.

**Comment by xfreebird** [comment]
That would be very useful since the `cocoapods 1.0.x` is using a new version of `xcodeproj` that doesn't downgrade the xcode configuration file to an older format
