### ISSUE TITLE
Error creating the Xcode group path to new modules

### ISSUE THREAD

**Issue by ismetanin** [rambler-digital-solutions/Generamba#129]
After "generamba gen TestThree swift_viper_module" I see in Xcode:
![2016-08-07 10 24 44 1](https://cloud.githubusercontent.com/assets/11653316/17461126/fe566060-5c91-11e6-99a6-3a9b07f5a47a.png)
![2016-08-07 10 31 14](https://cloud.githubusercontent.com/assets/11653316/17461142/7d4988e8-5c92-11e6-8cfe-90711646473a.png)
But in Finder all is well:
![2016-08-07 10 25 10](https://cloud.githubusercontent.com/assets/11653316/17461127/056fa8f2-5c92-11e6-8f2c-6cde40a2a054.png)
My Rambafile:

```
### Headers settings
company: 5Agency

### Xcode project settings
project_name: addressbook-ios
xcodeproj_path: AdressBook.xcodeproj

### Code generation settings section
# The main project target name
project_target: AdressBook

# The file path for new modules
project_file_path: /Users/Ivan/Documents/Work/addressbook-ios/AdressBook/Classes/Presentation/User Stories

# The Xcode group path to new modules
project_group_path: /Users/Ivan/Documents/Work/addressbook-ios/AdressBook/Classes/Presentation/User Stories

### Tests generation settings section
# The tests target name
test_target: AdressBookTests

# The file path for new tests
test_file_path: /Users/Ivan/Documents/Work/addressbook-ios/AdressBookTests

# The Xcode group path to new tests
test_group_path: /Users/Ivan/Documents/Work/addressbook-ios/AdressBookTests

### Dependencies settings section
podfile_path: Podfile

### Templates
templates:
- {name: swift_viper_module, local: '/Users/Ivan/Documents/Work/Helpers/generamba-modules/swift_viper_module'}
```

**Comment by etolstoy** [comment]
Hi, @lvinoeserdce! We'll investigate it asap.

**Comment by Beniamiiin** [comment]
@lvinoeserdce hi. I have already fixed this bug and we will release new version soon. Until then, write all paths in rambafile without slash('/') in begin and end of path and you will not have any problems. And, all paths in rambafile relative, example: `project_file_path: AdressBook/Classes/Presentation/User Stories`

**Comment by ismetanin** [comment]
@Beniamiiin hi! Thank you! I solved my problem with your help.
