### ISSUE TITLE
Error generate module with option :exclusive=>true in Podfile

### ISSUE THREAD

**Issue by atom-wintermute** [rambler-digital-solutions/Generamba#154]
.rvm/gems/ruby-2.2.1/gems/cocoapods-core-1.0.1/lib/cocoapods-core/podfile.rb:295:in `rescue in block in from_ruby':  (Pod::DSLError)
[!] Invalid`Podfile`file: Unsupported options`{:exclusive=>true}`for target`<target_name>`..

Podfile:
...
target '<target_name>', :exclusive => true do
    pod 'EasyMapping', '0.6.3'
    pod 'AFNetworking', '2.5.1'
    pod 'Typhoon', '3.3.4'
end
...

**Comment by etolstoy** [comment]
@atom-wintermute thanks for reporting! That's not a bug - update your Podfile to Cocoapods 1.0 syntax.
