### ISSUE TITLE
Custom commands support

### ISSUE THREAD

**Issue by noxt** [rambler-digital-solutions/Generamba#160]
Are you planning add support for custom commands or plugins system?

**Comment by etolstoy** [comment]
Hi, @noxt! Yes, we've just discussed it with some of our collegues and want to start working on that  feature. We'll start planning it near the end of October and after it post our roadmap here.

**Comment by etolstoy** [comment]
@noxt we've started working on Generamba 2.0! Check [our roadmap](https://github.com/rambler-digital-solutions/Generamba/blob/develop/docs/2.x/roadmap.md).
