### ISSUE TITLE
Catalog templates are not installing

### ISSUE THREAD

**Issue by xoxoj** [rambler-digital-solutions/Generamba#163]
<img width="482" alt="viper-error" src="https://cloud.githubusercontent.com/assets/1118723/19416099/26aa4aae-93ba-11e6-8387-7f270bc233ae.png">

Rambafile like this:
### Headers settings

company: AWWD
### Xcode project settings

project_name: QF
xcodeproj_path: QFile.xcodeproj
prefix: QF
### Code generation settings section
# The main project target name

project_target: QF
### Tests generation settings section
# The tests target name

test_target: QFTests
# The file path for new tests

test_file_path: /Users/stone/CP/QF/QFTests/
# The Xcode group path to new tests

test_group_path: QFTests
### Dependencies settings section

podfile_path: Podfile
### Templates

templates:
- {name: rviper_controller}
- {name: mvvm_controller}
- {name: adkrviper_controller}
- {name: swifty_viper}

**Comment by etolstoy** [comment]
@xoxoj what version of Generamba are you using? You can verufy it using command 'generamba version'.

**Comment by xoxoj** [comment]
@etolstoy Thank you! I use

Version: 1.2.0
Release date: 05.09.2016
Change notes: https://github.com/rambler-ios/Generamba/releases/tag/1.2.0

**Comment by etolstoy** [comment]
@xoxoj try to update to the latest version - we moved template catalog repo to another url recently, so previous versions of generamba won't work.

**Comment by xoxoj** [comment]
@etolstoy OK, tell me how to do update. Thanks.

**Comment by etolstoy** [comment]
@xoxoj, use command ’gem update generamba’

**Comment by xoxoj** [comment]
Hi, @etolstoy I have upgraded to the latest version, why is the same mistake.

Version: 1.2.2
Release date: 27.09.2016
Change notes: https://github.com/rambler-ios/Generamba/releases/tag/1.2.2

**Comment by etolstoy** [comment]
That's pretty awkward, because the latest version is 1.3.0: https://rubygems.org/gems/generamba
What prints out when you run 'gem update generamba'?

**Comment by xoxoj** [comment]
@etolstoy 
Updating installed gems
Nothing to update

I think I need use the rubygems for gem source....:D:D

**Comment by etolstoy** [comment]
Well, try to remove it and install again :)

gem uninstall generamba
gem install generamba

**Comment by xoxoj** [comment]
Hi @etolstoy  Perfect solution, you are good man! THX. I love Generamba!
