### ISSUE TITLE
Empty "code_files:" in .rambaspec

### ISSUE THREAD

**Issue by DevAlloy** [rambler-digital-solutions/Generamba#165]
In some cases it would be useful to leave this property empty, for example I just want to create only test files. Furthermore in case I clear this property by hands in installed templates Generamba creates files properly. But in case I try to install template with empty "code_files:", it doesn't pass validation.

**Comment by etolstoy** [comment]
I was sure that it's already implemented. Please, try to remove the key `code_files:` and reru  the generation.

**Comment by etolstoy** [comment]
Fixed, wait for the next release.
