### ISSUE TITLE
Can't install on macOS Sierra

### ISSUE THREAD

**Issue by notdetninja47** [rambler-digital-solutions/Generamba#166]
![2016-11-04 11 25 50](https://cloud.githubusercontent.com/assets/17043838/20000740/b4df634c-a281-11e6-92c9-5375e5079b70.png)

**Comment by etolstoy** [comment]
Hi, @notdetninja47 . Try to run this command with `--verbose` flag and paste your output.

```
sudo gem install generamba --verbose
```

**Comment by notdetninja47** [comment]
Hi, @etolstoy.

HEAD https://api.rubygems.org/api/v1/dependencies
200 OK
GET https://api.rubygems.org/api/v1/dependencies?gems=generamba
200 OK
Getting SRV record failed: DNS result has no information for _rubygems._tcp.api.rubygems.org
GET https://api.rubygems.org/api/v1/dependencies?gems=cocoapods-core,git,liquid,terminal-table,thor,xcodeproj
200 OK
GET https://api.rubygems.org/api/v1/dependencies?gems=activesupport,claide,colored,fuzzy_match,nap
200 OK
GET https://api.rubygems.org/api/v1/dependencies?gems=concurrent-ruby,i18n,minitest,tzinfo
200 OK
GET https://api.rubygems.org/api/v1/dependencies?gems=thread_safe
200 OK
/usr/local/lib/ruby/gems/2.3.0/gems/xcodeproj-1.2.0/LICENSE
/usr/local/lib/ruby/gems/2.3.0/gems/xcodeproj-1.2.0/README.md
/usr/local/lib/ruby/gems/2.3.0/gems/xcodeproj-1.2.0/bin/xcodeproj
/usr/local/lib/ruby/gems/2.3.0/gems/xcodeproj-1.2.0/lib/xcodeproj.rb
/usr/local/lib/ruby/gems/2.3.0/gems/xcodeproj-1.2.0/lib/xcodeproj/command.rb
/usr/local/lib/ruby/gems/2.3.0/gems/xcodeproj-1.2.0/lib/xcodeproj/command/config_dump.rb
/usr/local/lib/ruby/gems/2.3.0/gems/xcodeproj-1.2.0/lib/xcodeproj/command/project_diff.rb
/usr/local/lib/ruby/gems/2.3.0/gems/xcodeproj-1.2.0/lib/xcodeproj/command/show.rb
/usr/local/lib/ruby/gems/2.3.0/gems/xcodeproj-1.2.0/lib/xcodeproj/command/sort.rb
/usr/local/lib/ruby/gems/2.3.0/gems/xcodeproj-1.2.0/lib/xcodeproj/command/target_diff.rb
/usr/local/lib/ruby/gems/2.3.0/gems/xcodeproj-1.2.0/lib/xcodeproj/config.rb
/usr/local/lib/ruby/gems/2.3.0/gems/xcodeproj-1.2.0/lib/xcodeproj/config/other_linker_flags_parser.rb
/usr/local/lib/ruby/gems/2.3.0/gems/xcodeproj-1.2.0/lib/xcodeproj/constants.rb
/usr/local/lib/ruby/gems/2.3.0/gems/xcodeproj-1.2.0/lib/xcodeproj/differ.rb
/usr/local/lib/ruby/gems/2.3.0/gems/xcodeproj-1.2.0/lib/xcodeproj/gem_version.rb
/usr/local/lib/ruby/gems/2.3.0/gems/xcodeproj-1.2.0/lib/xcodeproj/helper.rb
/usr/local/lib/ruby/gems/2.3.0/gems/xcodeproj-1.2.0/lib/xcodeproj/plist.rb
/usr/local/lib/ruby/gems/2.3.0/gems/xcodeproj-1.2.0/lib/xcodeproj/plist/ffi.rb
/usr/local/lib/ruby/gems/2.3.0/gems/xcodeproj-1.2.0/lib/xcodeproj/plist/ffi/core_foundation.rb
/usr/local/lib/ruby/gems/2.3.0/gems/xcodeproj-1.2.0/lib/xcodeproj/plist/ffi/dev_tools_core.rb
/usr/local/lib/ruby/gems/2.3.0/gems/xcodeproj-1.2.0/lib/xcodeproj/plist/plist_gem.rb
/usr/local/lib/ruby/gems/2.3.0/gems/xcodeproj-1.2.0/lib/xcodeproj/project.rb
/usr/local/lib/ruby/gems/2.3.0/gems/xcodeproj-1.2.0/lib/xcodeproj/project/case_converter.rb
/usr/local/lib/ruby/gems/2.3.0/gems/xcodeproj-1.2.0/lib/xcodeproj/project/object.rb
/usr/local/lib/ruby/gems/2.3.0/gems/xcodeproj-1.2.0/lib/xcodeproj/project/object/build_configuration.rb
/usr/local/lib/ruby/gems/2.3.0/gems/xcodeproj-1.2.0/lib/xcodeproj/project/object/build_file.rb
/usr/local/lib/ruby/gems/2.3.0/gems/xcodeproj-1.2.0/lib/xcodeproj/project/object/build_phase.rb
/usr/local/lib/ruby/gems/2.3.0/gems/xcodeproj-1.2.0/lib/xcodeproj/project/object/build_rule.rb
/usr/local/lib/ruby/gems/2.3.0/gems/xcodeproj-1.2.0/lib/xcodeproj/project/object/configuration_list.rb
/usr/local/lib/ruby/gems/2.3.0/gems/xcodeproj-1.2.0/lib/xcodeproj/project/object/container_item_proxy.rb
/usr/local/lib/ruby/gems/2.3.0/gems/xcodeproj-1.2.0/lib/xcodeproj/project/object/file_reference.rb
/usr/local/lib/ruby/gems/2.3.0/gems/xcodeproj-1.2.0/lib/xcodeproj/project/object/group.rb
/usr/local/lib/ruby/gems/2.3.0/gems/xcodeproj-1.2.0/lib/xcodeproj/project/object/helpers/file_references_factory.rb
/usr/local/lib/ruby/gems/2.3.0/gems/xcodeproj-1.2.0/lib/xcodeproj/project/object/helpers/groupable_helper.rb
/usr/local/lib/ruby/gems/2.3.0/gems/xcodeproj-1.2.0/lib/xcodeproj/project/object/native_target.rb
/usr/local/lib/ruby/gems/2.3.0/gems/xcodeproj-1.2.0/lib/xcodeproj/project/object/reference_proxy.rb
/usr/local/lib/ruby/gems/2.3.0/gems/xcodeproj-1.2.0/lib/xcodeproj/project/object/root_object.rb
/usr/local/lib/ruby/gems/2.3.0/gems/xcodeproj-1.2.0/lib/xcodeproj/project/object/target_dependency.rb
/usr/local/lib/ruby/gems/2.3.0/gems/xcodeproj-1.2.0/lib/xcodeproj/project/object_attributes.rb
/usr/local/lib/ruby/gems/2.3.0/gems/xcodeproj-1.2.0/lib/xcodeproj/project/object_dictionary.rb
/usr/local/lib/ruby/gems/2.3.0/gems/xcodeproj-1.2.0/lib/xcodeproj/project/object_list.rb
/usr/local/lib/ruby/gems/2.3.0/gems/xcodeproj-1.2.0/lib/xcodeproj/project/project_helper.rb
/usr/local/lib/ruby/gems/2.3.0/gems/xcodeproj-1.2.0/lib/xcodeproj/project/uuid_generator.rb
/usr/local/lib/ruby/gems/2.3.0/gems/xcodeproj-1.2.0/lib/xcodeproj/scheme.rb
/usr/local/lib/ruby/gems/2.3.0/gems/xcodeproj-1.2.0/lib/xcodeproj/scheme/abstract_scheme_action.rb
/usr/local/lib/ruby/gems/2.3.0/gems/xcodeproj-1.2.0/lib/xcodeproj/scheme/analyze_action.rb
/usr/local/lib/ruby/gems/2.3.0/gems/xcodeproj-1.2.0/lib/xcodeproj/scheme/archive_action.rb
/usr/local/lib/ruby/gems/2.3.0/gems/xcodeproj-1.2.0/lib/xcodeproj/scheme/build_action.rb
/usr/local/lib/ruby/gems/2.3.0/gems/xcodeproj-1.2.0/lib/xcodeproj/scheme/buildable_product_runnable.rb
/usr/local/lib/ruby/gems/2.3.0/gems/xcodeproj-1.2.0/lib/xcodeproj/scheme/buildable_reference.rb
/usr/local/lib/ruby/gems/2.3.0/gems/xcodeproj-1.2.0/lib/xcodeproj/scheme/environment_variables.rb
/usr/local/lib/ruby/gems/2.3.0/gems/xcodeproj-1.2.0/lib/xcodeproj/scheme/launch_action.rb
/usr/local/lib/ruby/gems/2.3.0/gems/xcodeproj-1.2.0/lib/xcodeproj/scheme/macro_expansion.rb
/usr/local/lib/ruby/gems/2.3.0/gems/xcodeproj-1.2.0/lib/xcodeproj/scheme/profile_action.rb
/usr/local/lib/ruby/gems/2.3.0/gems/xcodeproj-1.2.0/lib/xcodeproj/scheme/test_action.rb
/usr/local/lib/ruby/gems/2.3.0/gems/xcodeproj-1.2.0/lib/xcodeproj/scheme/xml_element_wrapper.rb
/usr/local/lib/ruby/gems/2.3.0/gems/xcodeproj-1.2.0/lib/xcodeproj/user_interface.rb
/usr/local/lib/ruby/gems/2.3.0/gems/xcodeproj-1.2.0/lib/xcodeproj/workspace.rb
/usr/local/lib/ruby/gems/2.3.0/gems/xcodeproj-1.2.0/lib/xcodeproj/workspace/file_reference.rb
/usr/local/lib/ruby/gems/2.3.0/gems/xcodeproj-1.2.0/lib/xcodeproj/workspace/group_reference.rb
/usr/local/lib/ruby/gems/2.3.0/gems/xcodeproj-1.2.0/lib/xcodeproj/xcodebuild_helper.rb
ERROR:  While executing gem ... (TypeError)
    no implicit conversion of nil into String

**Comment by etolstoy** [comment]
What is your ruby version?

**Comment by notdetninja47** [comment]
MacBook-Pro-3:~ daniel$ ruby -v
ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-darwin16]

**Comment by Beniamiiin** [comment]
@notdetninja47 try to install `xcodeproj` separately - `sudo gem install xcodeproj` and then install `generamba` - `sudo gem install generamba`. It seems `xcodeproj` gem can't be install.

**Comment by notdetninja47** [comment]
MacBook-Pro-3:~ daniel$ sudo gem install xcodeproj

Fetching: CFPropertyList-2.3.3.gem (100%)
Successfully installed CFPropertyList-2.3.3
Fetching: nanaimo-0.2.2.gem (100%)
Successfully installed nanaimo-0.2.2
Fetching: xcodeproj-1.4.1.gem (100%)
ERROR:  While executing gem ... (TypeError)
    no implicit conversion of nil into String

**Comment by etolstoy** [comment]
I'll try to investigate this issue in more details, but I think that it's a problem with `rubygems` itself.

**Comment by etolstoy** [comment]
@notdetninja47 try this command:

```
sudo gem update --system
```
