### ISSUE TITLE
Generamba conflicts with Synx

### ISSUE THREAD

**Issue by mpsnp** [rambler-digital-solutions/Generamba#182]
Generamba crashes when [Synx](https://github.com/venmo/synx) gem installed.

For example `generamba init` log:

```
/Users/mpsnp/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/rubygems/specification.rb:2158:in `method_missing': undefined method `this' for #<Gem::Specification:0x3fed6f033eb8 generamba-1.3.0> (NoMethodError)
	from /Users/mpsnp/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/rubygems/specification.rb:1057:in `find_active_stub_by_path'
	from /Users/mpsnp/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:64:in `require'
	from /Users/mpsnp/.rvm/gems/ruby-2.3.0/gems/generamba-1.3.0/bin/generamba:3:in `<top (required)>'
	from /Users/mpsnp/.rvm/gems/ruby-2.3.0/bin/generamba:23:in `load'
	from /Users/mpsnp/.rvm/gems/ruby-2.3.0/bin/generamba:23:in `<main>'
	from /Users/mpsnp/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `eval'
	from /Users/mpsnp/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by etolstoy** [comment]
@mpsnp thanks for your report - I'll investigate it.

**Comment by etolstoy** [comment]
@mpsnp Can't reproduce it. BTW, generamba doesn't have `init` command. What should I do besides installing synx to get this error?

**Comment by mpsnp** [comment]
@etolstoy Don't know actually, i just installed both gems globally. BTW I'm using `rvm` and `ruby 2.3.0` as you maybe noticed from log.

Regarding command, it doesn't matter. Even just launching without any command produces error with the same log as above.

Initially i thought it's because of synx. But why other gems work fine (like cocoapods, fastlane, bundle, etc..)?

**Comment by etolstoy** [comment]
@mpsnp Seems that it's a problem in rubygems. What version do you use?

Try the following workarounds:

```
gem update --system
```
or
```
bundle clean
gem install executable-hooks
```

**Comment by mpsnp** [comment]
@etolstoy indeed, problem was in rubygems. `gem update --system` solved problem. Thanks for help. Sorry for blaming generamba
