### ISSUE TITLE
Если ли примеры?

### ISSUE THREAD

**Issue by mrstazzi** [rambler-digital-solutions/Generamba#187]
Добрый день.
Отличный кодогенератор, отличная книга про Viper.
Но есть ли живые примеры всего этого? Чтобы не только читать в теории, но и посмотреть как это реализуется на практике.
Очень интересует пример по использования Viper + Generamba - и все это на Swift (с Templates = swifty_viper). Как запускается, что используется, как делаются переходы и т.д.

Заранее благодарен

**Comment by etolstoy** [comment]
Привет!

Конечно, но на Objective-C. https://github.com/rambler-digital-solutions/rambler-it-ios

**Comment by mrstazzi** [comment]
Спасибо за ответ, но к сожалению на "Viper + Generamba - и все это на Swift (с Templates = swifty_viper)" это не очень похоже.

**Comment by etolstoy** [comment]
Со Swift нет, но к Генерамбе это не совсем относится - инструменту без разницы, какой код генерировать. С этим, скорее, в Issues Книги Вайпера.

**Comment by MaximBazarov** [comment]
@mrstazzi https://github.com/VIPER/swift-templates
@etolstoy пиарнулся)
