### ISSUE TITLE
illegal class name will be generated if modules contains "/"

### ISSUE THREAD

**Issue by alex-chan** [rambler-digital-solutions/Generamba#188]
For example, I'd like to use generamba like this 
`generamba gen Account/Login swifty_viper`

It will generate the right project structure, however ,the class name will be named `Account/Login`, which is illegal, and I'd like to use `Login` instead.

**Comment by Beniamiiin** [comment]
@alex-chan hi. After `gen` you should write module name, not module path, module path takes from `project_group_path` or from `--module_path` if it specified. Unfortunately, generamba can not do what do you want.

**Comment by alex-chan** [comment]
Well, thank you Beniamiiin, after put the `--module_path` , it did exactly what I want.
```
generamba gen Login --module_path SmartHome/Modules/Account swifty_viper
```
