### ISSUE TITLE
Optional files in template

### ISSUE THREAD

**Issue by mikhailmulyar** [rambler-digital-solutions/Generamba#196]
Hello. Thanks for great tool.
Basically i have situation described in this issue: https://github.com/rambler-digital-solutions/Generamba/issues/46
However my goal is a bit more complicated, since i want to have not only different methods, but also different files used or not in template depending on some parameter. Is it possible to achieve this behaviour? Or maybe implement this feature in future?

**Comment by MaximBazarov** [comment]
Hey @mikhailmulyar yes it possible, you can look here 
https://github.com/iOSViper/generamba-templates/blob/master/mvcr/mvcr.rambaspec

**Comment by mikhailmulyar** [comment]
@MaksimBazarov Great. Thanks!
