### ISSUE TITLE
Не получается выполнить установку Generamba

### ISSUE THREAD

**Issue by lgilyazov** [rambler-digital-solutions/Generamba#202]
Версия Xcode 9.3. Mac OS 10.13.4. Выдает такую ошибку.
> generamba setup
> The company name which will be used in the headers:
> The name of your project is 3pochmac. Do you want to use it? (yes/no) yes
> The project prefix (if any): ECH
> The path to a .xcodeproj file of the project is '3pochmac.xcodeproj'. Do you want to use it? (yes/no) yes
> /Users/lenar/.rvm/gems/ruby-2.4.1/gems/xcodeproj-1.4.2/lib/xcodeproj/project.rb:217:in 'initialize_from_file': [Xcodeproj] Unknown object version. (RuntimeError)
> 	from /Users/lenar/.rvm/gems/ruby-2.4.1/gems/xcodeproj-1.4.2/lib/xcodeproj/project.rb:102:in 'open'
> 	from /Users/lenar/.rvm/gems/ruby-2.4.1/gems/generamba-1.4.1/lib/generamba/cli/setup_command.rb:31:in 'setup'
> 	from /Users/lenar/.rvm/gems/ruby-2.4.1/gems/thor-0.19.1/lib/thor/command.rb:27:in 'run'
> 	from /Users/lenar/.rvm/gems/ruby-2.4.1/gems/thor-0.19.1/lib/thor/invocation.rb:126:in 'invoke_command'
> 	from /Users/lenar/.rvm/gems/ruby-2.4.1/gems/thor-0.19.1/lib/thor.rb:359:in 'dispatch'
> 	from /Users/lenar/.rvm/gems/ruby-2.4.1/gems/thor-0.19.1/lib/thor/base.rb:440:in 'start'
> 	from /Users/lenar/.rvm/gems/ruby-2.4.1/gems/generamba-1.4.1/bin/generamba:5:in '<top (required)>'
> 	from /Users/lenar/.rvm/gems/ruby-2.4.1/bin/generamba:23:in 'load'
> 	from /Users/lenar/.rvm/gems/ruby-2.4.1/bin/generamba:23:in '<main>'
> 	from /Users/lenar/.rvm/gems/ruby-2.4.1/bin/ruby_executable_hooks:15:in 'eval'
> 	from /Users/lenar/.rvm/gems/ruby-2.4.1/bin/ruby_executable_hooks:15:in '<main>'

**Comment by StarWars** [comment]
@Leklef you can find the solution in #203 , but we still need to wait for the official patch.
