### ISSUE TITLE
I want Indent size settings in Rambafile

### ISSUE THREAD

**Issue by noppefoxwolf** [rambler-digital-solutions/Generamba#223]
Rambafile
```
indent_size: 2 //default 4
```

**Comment by Beniamiiin** [comment]
Hi @noppefoxwolf. You can do it by simply changing indents in a template.

**Comment by noppefoxwolf** [comment]
Thanks. 
IMO: Modified templates ware deleted when re-install template.
If templates are updated, (for example to update of `swift`) this specification is a problem.
