### ISSUE TITLE
Is ruby 2.2. really need?

### ISSUE THREAD

**Issue by MaximBazarov** [rambler-digital-solutions/Generamba#32]
`ERROR:  Error installing generamba:
    generamba requires Ruby version >= 2.2.`

**Comment by etolstoy** [comment]
@MaksimBazarov current version is not working properly on ruby 2.0. We'll take time to investigate it.

**Comment by m4rr** [comment]
@MaksimBazarov why don't you update your Ruby environment?

**Comment by MaximBazarov** [comment]
@m4rr of course i did, but my point was: by default ruby version in OS X is 2.0 and would be great if installation go in one line without dependencies

But i don't think this is a bug

**Comment by m4rr** [comment]
Oh, got it. Didn't expect that default. (That's 'cause I use Rails and always have the last version.)

**Comment by etolstoy** [comment]
I agree that working with default ruby version is much more convenient - many of my colleagues spent much time upgrading their ruby version.

As far as I remember, that's the problem with ruby 2.0: https://github.com/rambler-ios/Generamba/issues/4

**Comment by etolstoy** [comment]
@mogol are you still interested in this issue?

**Comment by mogol** [comment]
Support ruby 2.0 was ended [two months ago](https://www.ruby-lang.org/en/news/2016/03/30/ruby-2-1-9-released/), ruby 2.1 - [one month ago](https://www.ruby-lang.org/en/news/2016/02/24/support-plan-of-ruby-2-0-0-and-2-1/). So I guess, it's not necessary to spend time on this issue. What do you think?

**Comment by etolstoy** [comment]
Well, @mogol, I agree :)
