### ISSUE TITLE
Need more information about dependencies 

### ISSUE THREAD

**Issue by MaximBazarov** [rambler-digital-solutions/Generamba#34]
Now not so clear how will dependency section works, I guess it will add in Podfile/Cartfile automatically, but will much better if it will described in docs

**Comment by MaximBazarov** [comment]
Also I think it is a killing feature and must be mentioned as a reason for use Generamba :)

**Comment by etolstoy** [comment]
Unfortunately, it's not implemented yet - auto-installing dependencies is in our plans for the near future. 
This field was added to keep the `rambaspec` and `Rambafile` formats consistent for the upcoming versions.
