### ISSUE TITLE
Can't find template by local fullpath

### ISSUE THREAD

**Issue by MaximBazarov** [rambler-digital-solutions/Generamba#35]
Rambafile:

```
....
templates:
- {name: bl_viper_uivc, path: /Volumes/DataStore/Projects/GenerambaTemplates/bl_viper_uivc}
```

error: 

```
Cannot find bl_viper_uivc.rambaspec in the template catalog. Try another name. (StandardError)
```

**Comment by etolstoy** [comment]
Thanks for reporting, your help is much appreciated! I'll investigate this issue as soon as possible. #36 should be a related one.

**Comment by etolstoy** [comment]
@MaksimBazarov Once again, my docs are not that great :(

You should use `local`, not `path`:

``` yaml
- {name: bl_viper_uivc, local: /Volumes/DataStore/Projects/GenerambaTemplates/bl_viper_uivc}
```

Sorry for the inconvenience! I'll update docs and `Rambafile` template.
