### ISSUE TITLE
undefined method `each' for nil:NilClass (NoMethodError)

### ISSUE THREAD

**Issue by tartakovsky** [rambler-digital-solutions/Generamba#37]
Hello!

Thanks for generamba :)

I'm getting an error when i'm trying to generate my module with the generamba:
[error.txt](https://github.com/rambler-ios/Generamba/files/45966/error.txt)

Here is my rambafile (.txt added to upload it to github):
[Rambafile.txt](https://github.com/rambler-ios/Generamba/files/45967/Rambafile.txt)

Here is my template's rambaspec:
[ica_module.rambaspec.txt](https://github.com/rambler-ios/Generamba/files/45970/ica_module.rambaspec.txt)

Looks like it is trying to process test files and i don't have any or something like that. 
Code-files are generated correctly, though.

**Comment by etolstoy** [comment]
Hi, @Flar49. Thanks for reporting! 👍

In my imaginary world everyone writes tests 😃Of course, that's an improper behavior - we'll fix it in the next release.

**Comment by etolstoy** [comment]
Fixed, the new version will be released shortly, maybe even this weekend.
