### ISSUE TITLE
Generamba as file converter

### ISSUE THREAD

**Issue by AndreyZarembo** [rambler-digital-solutions/Generamba#41]
Add new command to Generamba
`convert input_file [--output output_file] [--parser parser] [parser_arguments]`

It will convert one file types into another with one command.

This can be used to convert Objective-C files into Swift, CoreData model to classes with Mogenerator and Project Brief into application. 

Parser can be any Ruby, Bash script or console application.

**Comment by etolstoy** [comment]
@AndreyZarembo What is the exact profit of proxying the `convert` call to a specified parser instead of calling this parser directly?

**Comment by AndreyZarembo** [comment]
I think it should support this use cases:

1) ExternalConverter creates some output using input files and parameters from 'parser' file. Generamba puts output files into the project. e.g. Mogen creates models, Generamba puts them into special folder. Or it can be used to create new application icon with "Nightly build" badge. 

2) Parser is a ruby script that creates object like JSON. This object then can be mapped into liquid templates to get new files. E.g. we parse classes or protocols and create test templates for them

**Comment by etolstoy** [comment]
Still don't see any real use cases for this feature. Closing for now.
