### ISSUE TITLE
Add the ability to specify custom template catalogs in Rambafile

### ISSUE THREAD

**Issue by etolstoy** [rambler-digital-solutions/Generamba#44]
A couple of users asked to implement the ability of specifying custom template catalog urls somewhere in the Rambafile (just like cocoapods do).

**Comment by MaximBazarov** [comment]
Vote for this!

**Comment by Luccifer** [comment]
+1

**Comment by vasilenkoigor** [comment]
+1

**Comment by etolstoy** [comment]
I've updated the corresponding wiki page with new docs: https://github.com/rambler-ios/Generamba/wiki/Rambafile-Structure

```
catalogs:
- 'https://github.com/my-catalog1'
- 'https://github.com/my-catalog2'
```
