### ISSUE TITLE
Additional template parameters

### ISSUE THREAD

**Issue by MaximBazarov** [rambler-digital-solutions/Generamba#46]
It might be `-paramName paramvalue` or something like this, also would be great if it supports arrays

for example I have two templates which different only few lines, one of them contain method instantiation from SB and second one initialization from XIB and I can set `-initMethod SB` or  `-initMethod XIB` appropriate but applied to one template

**Comment by etolstoy** [comment]
Thanks, @MaksimBazarov! A very nice idea, I'll implement it ASAP.

**Comment by MaximBazarov** [comment]
@etolstoy why you removed this?

**Comment by etolstoy** [comment]
We didn't have resources to implement this feature yet - it will appear in one of the following releases.
