### ISSUE TITLE
Add support for multiple targets during generamba setup

### ISSUE THREAD

**Issue by serkrapiv** [rambler-digital-solutions/Generamba#49]
When you run '_generamba setup_' you are asked to select target for your modules (same thing for tests):

 `Select the appropriate target for adding your MODULES (type the index):`

But, since now we have support for multiple targets via editing Rambafile, it would be nice to be able to do it during setup.

**Comment by etolstoy** [comment]
Well, this was dine intentionally - in my opinion most of the project work with the single target - a multi-target option is for power users. The `generamba setup` command already consists of many steps and I'm afraid of complicating it even more.

I'll add the corresponding section to the wiki, so users would be able to add many targets manually.
