### ISSUE TITLE
Clarify generamba parameters usage

### ISSUE THREAD

**Issue by Brain89** [rambler-digital-solutions/Generamba#51]
Hello,

I need some more clarifications and examples on **generamba gen** usage with additional parameters. For example, it's unclear if I provide custom **--module-path** generamba will or will not create subfolder / subgroup with MODULE_NAME.

**Comment by etolstoy** [comment]
Hi, @Brain89. I'm still working on the documentation for this feature.
- **--module_file_path** results in creating a subfolder in the filesystem,
- **--module_group_path** results in creating a subgroup in Xcode hierarchy,
- **--module_path** results in creating both subfolder and corresponding subgroup.

**Comment by etolstoy** [comment]
I've finally prepared docs for generamba commands: https://github.com/rambler-ios/Generamba/wiki/Available-commands
