### ISSUE TITLE
Incorrect behavior when generate module which already exists

### ISSUE THREAD

**Issue by MaximBazarov** [rambler-digital-solutions/Generamba#52]
When regenerate module with name already exists 
1) No any warnings about deletion my files (it possible I already have some code here)
2) Incorrect deletion from project, some files paths corrupted in _compiled sources_
![SS](https://monosnap.com/file/pex7fBG9uSVKcV5EO0mpkgNL0yCFah.png)

steps:

```
generamba gen RootNavigation  bl_viper_default_gt
```

and again 

```
generamba gen RootNavigation  bl_viper_default_gt
```

**Comment by etolstoy** [comment]
@MaksimBazarov thanks for reporting! I've already encountered [a very similar problem](https://github.com/rambler-ios/Generamba/issues/20), seems that my fix wasn't enough. I'll investigate this behavior (described under p.2).

And a nice idea about posting warnings about deletion - I'll plan it for one of the upcoming versions!
