### ISSUE TITLE
Unexpected behavior when use --module_path 

### ISSUE THREAD

**Issue by MaximBazarov** [rambler-digital-solutions/Generamba#53]
When i use this option I expect that generamba will create `MyModuleName` folder in `Module/Path/` but it put module content in  `Module/Path/` instead

For example: 

```
generamba gen SomeModule some_template  --module_path UserStories/Main/
```

Expected result is: `UserStories/Main/SomeModule` contains my module files appropriate template
Actual result is:  `UserStories/Main/` contains my module files

**Comment by etolstoy** [comment]
@MaksimBazarov that's definitely a bug - I'll fix it ASAP.

**Comment by MaximBazarov** [comment]
also references to files in target folder was removed (in `Module/Path/`)
