### ISSUE TITLE
Can generamba be used to generate swift modules?

### ISSUE THREAD

**Issue by appleios** [rambler-digital-solutions/Generamba#61]
It may seem stupid question, but I can't find any docs about if it supports swift.

**Comment by mogol** [comment]
Generamba is only generator,
it supports all languages by using different templates.
We have already PR with Swift template. Some corrections and you will be able to use Swift from box.

**Comment by appleios** [comment]
PR? Can you provide a link to an example of such template?

**Comment by mogol** [comment]
https://github.com/rambler-ios/Generamba/pull/59

**Comment by mogol** [comment]
Here https://github.com/rambler-ios/generamba-catalog/pull/3

**Comment by appleios** [comment]
Thank you. I've succeeded on generation.
