### ISSUE TITLE
Can we introduce something similar to view partials in rails (for duplicated parts of views)

### ISSUE THREAD

**Issue by appleios** [rambler-digital-solutions/Generamba#62]
Im templates there are a lot of duplicated code, for example:

```
//
//  {{ module_info.name }}{{ module_info.file_name }}
//  {{ module_info.project_name }}
//
//  Created by {{ developer.name }} on {{ date }}.
//  Copyright {{ year }} {{ developer.company }}. All rights reserved.
//
```

Some tests files also need the same imports:

``` swift
import Quick  // https://github.com/Quick/Quick/blob/master/Documentation/QuickExamplesAndGroups.md
import Nimble // https://github.com/Quick/Nimble
```

It would be great, if we could use some partials to generate duplicated parts of templates.

**Comment by etolstoy** [comment]
@appleios thanks for a very nice idea, we'll definitely implement it in one of the upcoming versions!

**Comment by mogol** [comment]
Really cool idea.

**Comment by etolstoy** [comment]
Looks like Liquid [has this ability by design](https://docs.shopify.com/themes/liquid-documentation/tags/theme-tags#include), should be really easy to implement. I'll investigate it closely and update one of our templates with partials.

**Comment by etolstoy** [comment]
https://github.com/rambler-ios/Generamba/wiki/Template-Structure#Snippets
