### ISSUE TITLE
Don't set target in swift projects

### ISSUE THREAD

**Issue by MaximBazarov** [rambler-digital-solutions/Generamba#65]
Steps: 
1. Create new swift project
2. Set up generamba and templates
3. Generamba gen

ER: Files created and included in project's target
AR: Files created and included in project but didn't include in target

**Comment by etolstoy** [comment]
@mogol has already reported this issue. Herman, did you take any steps to fix it?

**Comment by mogol** [comment]
@igrekde ,
I fixed this in develop branch.

**Comment by etolstoy** [comment]
@mogol thanks for taking this issue and adding unit tests! 🎉
