### ISSUE TITLE
Automatic tests generation based on protocols and class interfaces

### ISSUE THREAD

**Issue by etolstoy** [rambler-digital-solutions/Generamba#71]
It would be great to auto generate a tests suite based on protocols/interfaces. E.g. it;s useful for VIPER modules - user adds some methods to `ViewInput.h`/`ViewOutput.h`/..., then runs something like `generamba gen-tests BrandNewModule` - and voila!

At a first glance I see a couple of questions:
- What should we do, if there are already some tests generated? Completely remove them, or do something more intelligent?
- Where should the naming conventions of converting method names to test names be described?
- How to parse these protocols and interfaces? @mogol has suggested to use `llvm` and work with already built `AST` - this possibility should be investigated properly.

This issue can be referenced more generally - if we somehow add the ability to preprocess some input code files from the project, we would be able to do a lot of other great things - e.g. connecting VIPER modules on the fly.

**Comment by mogol** [comment]
We could ask @complexityclass some thoughts about this.

**Comment by etolstoy** [comment]
Closed as absolete.
