### ISSUE TITLE
Enhance `generamba template list` to browse custom catalogs

### ISSUE THREAD

**Issue by etolstoy** [rambler-digital-solutions/Generamba#74]
Currently `generamba template list` prints out templates from the shared catalog only.

When we are in the project directory, it should list all catalogs from the Rambafile.

**Comment by mogol** [comment]
How can I list all available templates?

**Comment by etolstoy** [comment]
Via the aforementioned command: `generamba template list` (it's the list from https://github.com/rambler-ios/generamba-catalog)
