### ISSUE TITLE
Non human exception when wrong template name or catalog

### ISSUE THREAD

**Issue by MaximBazarov** [rambler-digital-solutions/Generamba#77]
When I miswrite the template_name it was appear this error:

```
(Rambafile): found unexpected ':' while scanning a plain scalar at line 38 column 38 
(Psych::SyntaxError)
```

Will be great to have more clear error text, like "There aren't templates with name XXX in catalog YYY"

**Comment by etolstoy** [comment]
@MaksimBazarov can you specify the Rambafile templaes section contents? We are already handling this issue with an error: `Cannot find test in any catalog. Try another name.`.

**Comment by etolstoy** [comment]
Closing the issue as outdated.
