### ISSUE TITLE
Arguments for `generamba gen Name modulename`

### ISSUE THREAD

**Issue by appleios** [rambler-digital-solutions/Generamba#80]
Arguments for `generamba gen Name modulename --project_file_path app/tableView/cells/modules`.

At least there should be a way to change all keys from Rambafile, e.g.
- project_target
- project_file_path
- project_group_path (if not provided, equal to project_file_path)
- etc

**Comment by etolstoy** [comment]
Hi, @appleios . You can already use these flags: https://github.com/rambler-ios/Generamba/wiki/Available-Commands#module-generation

**Comment by appleios** [comment]
Thank you!
