### ISSUE TITLE
Can we use constants from rambafile in templates?

### ISSUE THREAD

**Issue by appleios** [rambler-digital-solutions/Generamba#81]
I need a `project_name` key from Rambafile in template for

``` swift
@testable import {{ project_name }}
```

Can I get it?

**Comment by etolstoy** [comment]
@appleios once again, you can check the corresponding page in our WIki: https://github.com/rambler-ios/Generamba/wiki/Template-Structure.

**Comment by appleios** [comment]
Sorry, I should've looked into docs first.

**Comment by etolstoy** [comment]
@appleios That's ok - we added docs just a few weeks ago.
