### ISSUE TITLE
Get "Liquid error: This liquid context does not allow includes." on all files in just generated module

### ISSUE THREAD

**Issue by spase84** [rambler-digital-solutions/Generamba#93]
Just trying Generamba and can't get well generated module

Steps i'm doing:

1) Create "Single View Application" via Xcode (version 7.2)
2) run "pod init" in project directory (cocoapods version is 0.39.0)
3) Write to Podfile some dependencies ('Typhoon', 'OCMock', 'RamblerTyphoonUtils', 'ViperMcFlurry')
4) Get Pods installed via "pod install"
5) Follow this part [https://github.com/rambler-ios/Generamba#using](https://github.com/rambler-ios/Generamba#using)
6) At this point i have Module generated, but each file in generated module starts with "Liquid error: This liquid context does not allow includes."

i have installed:

ruby 2.2.3p173 (2015-08-18 revision 51636) [x86_64-darwin15]
gem liquid (3.0.6)
generamba version 0.7.3

my Rambafile is:

```
### Headers settings
company: some_company

### Xcode project settings
project_name: Testapp
xcodeproj_path: Testapp.xcodeproj
prefix: AP

### Code generation settings section
# The main project target name
project_target: Testapp

# The file path for new modules
project_file_path: Modules

# The Xcode group path to new modules
project_group_path: Modules

### Tests generation settings section
# The tests target name
test_target: Testapp

# The file path for new tests
test_file_path: Tests

# The Xcode group path to new tests
test_group_path: Tests

### Dependencies settings section
podfile_path: Podfile


### Templates
templates:
- {name: rviper_controller}
```

**Comment by Beniamiiin** [comment]
Tomorrow we release new version and this problem will be fixed, now you can download Generamba from repository and in terminal go to Generamba directory and execute command:
`sudo gem uninstall generamba && sudo gem build generamba.gemspec && sudo gem install generamba`

**Comment by spase84** [comment]
it fixed the problem. Thank you!
