### ISSUE TITLE
Easy setup template path to local templates in Rambafile

### ISSUE THREAD

**Issue by Koshub** [rambler-digital-solutions/Generamba#94]
It would be very good if user could setup local_template_name as relative to rambafile path or current generamba exec folder, to customise templates for project
Existing:
`{name: local_template_name, local: 'absolute path'}`
Proposal (well something like this one):
`{name: local_template_name, local: 'path', absolute_path: false}`

**Comment by Koshub** [comment]
Oh, seems it's available without any other keys

**Comment by etolstoy** [comment]
Yes, it's available :)
