### ISSUE TITLE
Layout issue in "Summary for gen module"

### ISSUE THREAD

**Issue by valnoc** [rambler-digital-solutions/Generamba#95]
First of all, thx for generamba))

I have a problem with human readable output of Summary table. 
(generamba gen Module rviper_controller)

The problem is in "templates" row (last row) of this table. I actively use my custom templates, so i have a number of them. You enumerate templates using comma.

```
| templates          | rviper_controller, tmpl1, tmpl2, tmpl3, tmpl4 |
```

As template names are not as short as "tmpl1", this row goes out of the screen and results in 

```
| test_file_path     | asdasd
            |
| test_group_path    | asdasd
            |
| podfile_path       | Podfile
            |
| templates          | rviper_controller, tmpl1, tmpl2, 
tmpl3, tmpl4 |
```

Table is broken and totally unreadable. To handle this I have to enlarge terminal screen.

What if just enumerate templates using new line? Like

```
| test_file_path     | asdasd              |
| test_group_path    | asdasd              |
| podfile_path       | Podfile             |
| templates          | rviper_controller   |
|                    | tmpl1               |
|                    | tmpl2               |
|                    | tmpl3               |
|                    | tmpl4               |
+--------------------+---------------------+
```

**Comment by Beniamiiin** [comment]
@valnoc thanks for reporting! We will fix this in next release.
