### ISSUE TITLE
Failed adding files to project

### ISSUE THREAD

**Issue by rmncv** [rambler-digital-solutions/Generamba#96]
Hi!
- I've installed generamba with accordance to github instructions
- My rambafile looks like:

```
 ### Headers settings
company: Nosiy Miner

### Xcode project settings
project_name: fitnessgeek
xcodeproj_path: FitnessGeek.xcodeproj

### Code generation settings section
# The main project target name
project_target: FitnessGeek

# The file path for new modules
project_file_path: FitnessGeek/UserStory/

# The Xcode group path to new modules
project_group_path: FitnessGeek/UserStory/

### Dependencies settings section
podfile_path: Podfile

### Templates
templates:
- {name: my_swifty_viper, local: 'my_swifty_viper'}
#- {name: remote_template_name, git: 'https://github.com/igrekde/remote_template'}
#- {name: catalog_template_name}
```
- Creating new module, all files created at the correct path and adding to xcode (visually) correct as well
  but files are missing (screen: http://i.imgur.com/tgDPoCD.png). I checked file inspector and found out that absolute path is incorrect. It's look like: 
  /Users/UserStory/TestModule/Assembly/TestModuleAssembly.swift but it should look like:
  /Users/username/fitnessgeek/FitnessGeek/UserStory/TestModule/Assembly/TestModuleAssembly.swift

If I will set project_file_path to 'FitnessGeek' everything will be added correctly, but files will be created at the folder's root, and this is not what I'm want to

**Comment by Beniamiiin** [comment]
@rmncv hi! 
1. Can you add this `- {name: swifty_viper}` in Rambafile and execute `generamba template install && generamba gen TestModule1 swifty_viper`. And look `TestModule1` folder, problem is not solved?
2. Could you attach example project, in which there is this problem.

**Comment by etolstoy** [comment]
The author is not responding, so I'm closing this issue for now. @rmncv, if your problem still exists, feel free to reopen the ticket.

**Comment by hassan31** [comment]
@Beniamiiin @etolstoy 
I'm also trying to create modules following the instructions, but it gives me an error on the terminal and not creating the module for me. I'm trying to add Login Module under temples section in`rambafile ` but its not working for me. Please see attached screen shot:

<img width="492" alt="screenshot 2019-03-06 at 3 57 51 pm" src="https://user-images.githubusercontent.com/3063382/53913148-a0134e00-4028-11e9-8a98-e37bc6c8193c.png">

<img width="855" alt="screenshot 2019-03-06 at 3 56 43 pm" src="https://user-images.githubusercontent.com/3063382/53913088-7b1edb00-4028-11e9-8af1-0425763553f0.png">

Please guide me in this regard.

Thanks,
Hassan

**Comment by hassan31** [comment]
And when I try to install the temple by this command `generamba template install`

Its giving me below error:

<img width="483" alt="screenshot 2019-03-06 at 3 59 16 pm" src="https://user-images.githubusercontent.com/3063382/53913249-e799da00-4028-11e9-9e5e-f2ac827963c2.png">
