### ISSUE TITLE
Generate with project and tests targets in command line

### ISSUE THREAD

**Issue by rowwingman** [rambler-digital-solutions/Generamba#97]
Is it possible to set custom project and test target in command line for gen command?
Is it possible to copy tests inside module folder "Tests"?

**Comment by etolstoy** [comment]
Hi, @marko1503!

> Is it possible to set custom project and test target in command line for gen command?

Check the documentation for the `generamba gen` command: https://github.com/rambler-ios/Generamba/wiki/Available-Commands#module-generation

> Is it possible to copy tests inside module folder "Tests"?

I haven't tried it, but I don't think anything may stop you.
