### ISSUE TITLE
Remove adding module name in module_group_path  if it set from cli

### ISSUE THREAD

**Issue by IvanUshakov** [rambler-digital-solutions/Generamba#98]
When I generate module using this command:

```
generamba gen MyModule module --module-group-path projectName/Scenarios
```

Generamba adds MyModule folder in projectName/Scenarios by default. But in my opinion if I change destination with module-group-path option it should add files in _same_ path, that I set in that option

So, instead

```
projectName/Scenarios/MyModule
```

it should be

```
projectName/Scenarios
```

**Comment by etolstoy** [comment]
@IvanUshakov Thanks for your suggestion, seems reasonable.

**Comment by etolstoy** [comment]
After discussion with @Beniamiiin we decided that current behavior is more predictable. If some more people will request for this feature, we'll revisit to it.
